name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  PR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: go
      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          fuzz-seconds: 300
          mode: "code-change"
          github-token: ${{ secrets.GITHUB_TOKEN }}
